[project]
name = "goit-pycore-hw-04"
version = "0.1.0"
description = "Homework 04 for GoIT Python Core Course"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "colorama>=0.4.6",
    "types-colorama>=0.4.15.20250801",
]
